### ISSUE TITLE
Integration with ProfilesSpawner?

### ISSUE THREAD

**Issue by statiksof** [cmd-ntrf/slurmformspawner#9]
Hi @cmd-ntrf , 

I  just found this repository and it is quite similar to what I whant to achieve. Is it possible to use ```SlurmFormSpawner``` a ```child_profile```? something like this:

```
c.ProfilesSpawner.profiles = [
       ("Host process", 'local', 'jupyterhub.spawner.LocalProcessSpawner', {'ip':'0.0.0.0'} ),
       ('Advanced Slurm Options', 'advanced', 'slurmformspawner.SlurmFormSpawner', 
       {}),
              
 ]
```
Currently it detects the spawner class but shows not form.

**Comment by cmd-ntrf** [comment]
Hi,

Unfortunately, it is not possible to use ProfileSpawner with another spawner that also requires the usage of a form. This is an interesting problem to which there is no easy solution that I can think of for now, but wrapspawner developpers might have some ideas. You should raise the issue in wrapspawner repo (https://github.com/jupyterhub/wrapspawner).

**Comment by statiksof** [comment]
https://github.com/jupyterhub/wrapspawner/issues/38

**Comment by statiksof** [comment]
This issue can be closed. I managed to get it works but the code is not clean to share it.

**Comment by cmd-ntrf** [comment]
I talked with wrapspawner main developper earlier this month, and the consensus was that if it could work, it was a pleasant surprise.

Could you post a gist of your code so either I or someone else could get an idea of what had to be modify and maybe come up with a solution? And maybe list the functions you had to modify to make it work? That would be really useful.

**Comment by statiksof** [comment]
sure, I will. Also I had to modify/adapt ```slurmformspawner``` to fit our HPC.
